In [3]:
import numpy as np

In [5]:
# Get version of installed numpy
print(np.__version__)

2.1.0


In [24]:
# 0 dimension
arrary_0 = np.array(62) 
print(arrary_0)
print("Dimensions in array_0 are: ", arrary_0.ndim)
print("shape arrary_0:", arrary_0.shape)

62
Dimensions in array_0 are:  0
shape arrary_0: ()


In [25]:
# 1 dimension
arrary_1 = np.array([1,2,3,4,5,6]) 
print(arrary_1)
print("Dimensions in arrary_1 are: ", arrary_1.ndim)
print("shape arrary_1:", arrary_1.shape)

[1 2 3 4 5 6]
Dimensions in arrary_1 are:  1
shape arrary_1: (6,)


In [26]:
# 2 dimensions
array_2 = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
) 
print(array_2)
print("Dimensions in array_2 are: ", array_2.ndim)
print("shape array_2:", array_2.shape)

[[1 2 3]
 [4 5 6]]
Dimensions in array_2 are:  2
shape array_2: (2, 3)


In [27]:
# 3 dimensions
array_3 = np.array(
    [
        [
            [1, 2, 3], 
            [4, 5, 6]
        ], 
        [
            [1, 2, 3], 
            [4, 5, 6]
        ]
    ])
print(array_3)
print("Dimensions in array_3 are: ", array_3.ndim)
print("shape array_3:", array_3.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Dimensions in array_3 are:  3
shape array_3: (2, 2, 3)


In [28]:
# 5 dimension
array_5 = np.array([1,2,3,4], ndmin=5)
print(array_5)
print("Dimensions in array_5 are: ", array_5.ndim)
print("shape array_5:", array_5.shape)

[[[[[1 2 3 4]]]]]
Dimensions in array_5 are:  5
shape array_5: (1, 1, 1, 1, 4)


In [29]:
# Feature matriz: 5 sample , each with [height, weight]
data = np.array(
    [
        [170, 65],
        [180, 80],
        [160, 55],
        [175, 70],
        [165, 60],
    ]
)
print("Features:\n", data)
print("\nDimensions in data are: ", data.ndim)
print("shape:", data.shape)

Features:
 [[170  65]
 [180  80]
 [160  55]
 [175  70]
 [165  60]]

Dimensions in data are:  2
shape: (5, 2)


In [33]:
# Mean height and mean weight
# Mean => sum all numbers, then divid by count of numbers
print("Mean Height:", np.mean(data[:,0])) # coulmn 0
print("Mean weight:", np.mean(data[:,1])) # coulmn 1

print("Mean Height(custome):", np.mean(data[0:2,0])) # row effected has: 0,1 

Mean Height: 170.0
Mean weight: 66.0
Mean Height(custome): 175.0


In [39]:
# Generate random dataset
# 100 sample, 3 feature (values between 0 and  1)
random_dataset = np.random.rand(100, 3)
print("Dimensions in random_dataset are: ", random_dataset.ndim)
print("shape random_dataset:", random_dataset.shape)

print(random_dataset[:5])

Dimensions in random_dataset are:  2
shape random_dataset: (100, 3)
[[0.90182678 0.63417107 0.82810934]
 [0.49295512 0.66691894 0.88316823]
 [0.35633901 0.43369653 0.59388222]
 [0.73648558 0.9997599  0.81503566]
 [0.42084171 0.46237962 0.70713681]]


In [43]:
# Multiplying two matrices
a = np.array(
    [
        [1,2],
        [3,4]
    ]
)
b = np.array(
    [
        [5,6],
        [7,8]
    ]
)
result = a*b
print(result)

[[ 5 12]
 [21 32]]


In [46]:
# Tranpose  of matrix
# swap rows and columns
array = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
) 
print("Original shape of array:", array.shape)
print("Tranpose shape of array:", array.T.shape)

Original shape of array: (2, 3)
Tranpose shape of array: (3, 2)


In [50]:
# softmax function (classification)
# activation function in nerual network

z = np.array([2.0,1.0,0.1])
softmax = np.exp(z) / np.sum(np.exp(z))
print("Softmax result: ", softmax)

Softmax result:  [0.65900114 0.24243297 0.09856589]


In [51]:
# Mean Squared Error (MSE)
y_true = np.array([3, -0.5, 2, 7])
y_pred = np.array([2.5, 0.0, 2, 8])
mse = np.mean((y_true - y_pred) ** 2)
print("MSE:", mse)

MSE: 0.375
